Admin
onioncracker/spacey-frontend-2021 pull request #19
Opened 2021-06-13 22:49 UTC by mashg

2021-06-14 11:13 UTC, MJiason approved these changes

2021-06-15 06:29 UTC, Dima2057 requested changes

2021-06-15 06:29 UTC, Dima2057 commented on src/app/store/service/employee/employeeService.ts
> +// }
Please, remove this stub. Store it in local version.

2021-06-15 06:29 UTC, Dima2057 commented on src/app/store/service/employee/employeeService.ts
> +  // private editEmployeeUrl = this.employeeUrl + '/update';
Please, remove this stub. Store it in local version.

2021-06-15 06:29 UTC, Dima2057 commented on src/app/components/admin-manage/admin-employee.component.ts
> +  // private searchText$ = new Subject<string>();
Please, remove this stub. Store it in local version.

2021-06-15 06:29 UTC, Dima2057 commented on src/app/components/admin-edit/admin-edit.component.ts
> +}
Please, remove this stub. Store it in local version.

2021-06-15 06:29 UTC, Dima2057 commented on src/app/components/admin-edit/admin-edit.component.html
> +<!--</form>-->
Please, remove this stub. Store it in local version.

2021-06-15 06:29 UTC, Dima2057 commented on src/app/components/admin-add/admin-add.component.html
> +        <!--        </mat-error>-->
Please, remove this stub. Store it in local version.

2021-06-15 10:47 UTC, closed without merging